import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const SEED=[{name:'Ingeniería en Sistemas Computacionales',color:'#2463eb'},{name:'Ingeniería Mecatrónica',color:'#e67e22'},{name:'Ingeniería Aeroespacial',color:'#8b5cf6'}];
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const initial={name:'',matricula:'',career:'',term:'',group:'',email:'',role:'Estudiante'};
const esc=(value='')=>String(value);
function Brand({onSettings}){return <header className="topbar"><div className="brand"><div className="seal"><img className="brand-logo" src="./cesba-logo.png" alt="Logo institucional CESBA"/></div></div><button className="iconbtn" aria-label="Ajustes" onClick={onSettings}>⚙</button></header>}
function Card({data,photo,color,back=false,qr='',ripple=null,buildKey=0}) {
  const particleColors = data.career?.toLowerCase().includes('sistemas')
    ? ['#d6a6ff','#fff8ff','#a978ff']
    : data.career?.toLowerCase().includes('mecatr')
      ? ['#ffb36b','#fff5e8','#8de9ff']
      : data.career?.toLowerCase().includes('aeroespacial')
        ? ['#9bd8ff','#f4fbff','#8b9cff']
        : [color,'#ffffff','#d8e5ff'];
  const sparkles=useMemo(()=>Array.from({length:19},(_,i)=><i key={i} className="spark" style={{left:`${(i*37+8)%97}%`,top:`${(i*61+13)%87}%`,width:i%4===0?3:2,height:i%4===0?3:2,color:particleColors[i%particleColors.length],'--spark-x':`${((i*31)%92)-46}px`,'--spark-y':`${((i*17)%52)-26}px`,'--spark-time':`${16+(i%6)*3}s`,'--spark-delay':`${-((i*7)%23)}s`}}/>),[data.career,color]);
  const buildParticles=Array.from({length:42},(_,i)=><i key={`${buildKey}-${i}`} style={{'--px':`${((i*43)%100)-50}%`,'--py':`${((i*67)%100)-50}%`,'--delay':`${(i%9)*18}ms`,'--particle-color':particleColors[i%particleColors.length]}}/>);
  return <div className="credential-float" style={{'--float-color':color}}><article className={`card${back?' card-back':''}`} style={{'--career':color}}>{ripple&&<span key={ripple.key} className="touch-ripple" style={{left:ripple.x,top:ripple.y}}/>}{buildKey>0&&<div key={buildKey} className="build-particles">{buildParticles}</div>}{back?<><h3>IDENTIDAD ACADÉMICA</h3><div className="qrbox">{qr&&<img src={`data:image/png;base64,${qr}`} alt="Código QR con los datos académicos"/>}</div><p>Escanea para consultar los datos académicos del titular.</p><div className="cardfoot cardback-foot"><span>CESBA · CREDENCIAL DIGITAL</span><b><img className="card-foot-logo" src="./cesba-owl.png" alt="Logo búho CESBA"/></b></div></>:<><div className="sparkles">{sparkles}</div><div className="cardhead"><div className="cardcrest"><img className="crest-image" src="./cesba-logo.png" alt="Logo CESBA"/></div><div className="school">CREDENCIAL DIGITAL<small>IDENTIFICACIÓN UNIVERSITARIA</small></div><div className="chip"/></div><div className="cardbody"><div className="avatar">{photo?<img src={photo} alt="Foto del estudiante"/>:<span>✦</span>}</div><div className="identity"><div className="tag">{esc(data.role||'Estudiante').toUpperCase()} · {esc(data.matricula||'00000000')}</div><h2>{esc(data.name||'Nombre y apellidos')}</h2><div className="major">{esc(data.career||'Tu carrera')}</div><div className="idrow"><div className="idnum"><label>MATRÍCULA</label><strong>{esc(data.matricula||'00000000')}</strong></div><div className="idterm"><label>PERIODO · GRUPO</label><strong>{esc(data.term||'Semestre')} · {esc(data.group||'—')}</strong></div></div></div></div><div className="cardfoot"><span>{esc(data.email||'correo@cesba.edu.mx')}</span><b>CESBA&nbsp;<img className="card-foot-logo" src="./cesba-owl.png" alt="Logo búho CESBA"/></b></div></>}</article><div className="credential-shadow"/></div>
}
function hexToHsv(hex) {
  const value=hex.replace('#',''); if(!/^[0-9a-f]{6}$/i.test(value)) return {h:260,s:.72,v:.93};
  const r=parseInt(value.slice(0,2),16)/255,g=parseInt(value.slice(2,4),16)/255,b=parseInt(value.slice(4,6),16)/255;
  const max=Math.max(r,g,b),min=Math.min(r,g,b),delta=max-min;let h=0;
  if(delta){if(max===r)h=60*(((g-b)/delta)%6);else if(max===g)h=60*((b-r)/delta+2);else h=60*((r-g)/delta+4)}
  return {h:(h+360)%360,s:max===0?0:delta/max,v:max};
}
function hsvToHex({h,s,v}) {
  const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;let rgb=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];
  return '#'+rgb.map(n=>Math.round((n+m)*255).toString(16).padStart(2,'0')).join('').toUpperCase();
}
function ColorPickerDialog({initialColor,onCancel,onApply}) {
  const [hsv,setHsv]=useState(()=>hexToHsv(initialColor));const [hex,setHex]=useState(initialColor.toUpperCase());const wheel=useRef(null);const drag=useRef(false);
  const color=hsvToHex(hsv);
  const update=next=>{setHsv(next);setHex(hsvToHex(next))};
  const pickPoint=e=>{if(!wheel.current)return;const r=wheel.current.getBoundingClientRect(),cx=r.width/2,cy=r.height/2,dx=e.clientX-r.left-cx,dy=e.clientY-r.top-cy;const radius=Math.min(1,Math.sqrt(dx*dx+dy*dy)/(Math.min(r.width,r.height)/2));update({...hsv,h:(Math.atan2(dy,dx)*180/Math.PI+360)%360,s:radius})};
  const setHexValue=value=>{setHex(value);if(/^#?[0-9a-f]{6}$/i.test(value)){const clean=value.startsWith('#')?value:'#'+value;setHsv(hexToHsv(clean))}};
  const pointer=e=>{if(e.type==='pointerdown'){drag.current=true;e.currentTarget.setPointerCapture(e.pointerId)}if(drag.current)pickPoint(e);if(e.type==='pointerup'||e.type==='pointercancel')drag.current=false};
  const quick=['#EF476F','#F15BB5','#9B5DE5','#6C63FF','#4361EE','#168AAD','#00B4D8','#06D6A0','#70C1B3','#A7C957','#F9C74F','#F8961E','#F3722C','#F8F9FA','#8996AA'];
  const r=100*(hsv.s),a=hsv.h*Math.PI/180;
  return <div className="color-dialog-backdrop" onClick={onCancel}><section className="color-dialog" onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-label="Personalizar color"><header className="picker-header"><div><small>COLOR DE CARRERA</small><h2>Elige tu tono</h2></div><button className="picker-close" onClick={onCancel} aria-label="Cerrar">×</button></header><div className="picker-body"><div ref={wheel} className="color-wheel" style={{"--shade":(1-hsv.v).toFixed(2)}} onPointerDown={pointer} onPointerMove={pointer} onPointerUp={pointer} onPointerCancel={pointer} role="slider" aria-label="Selector de tono y saturación" tabIndex="0"><i className="wheel-marker" style={{left:`calc(50% + ${Math.cos(a)*r}px)`,top:`calc(50% + ${Math.sin(a)*r}px)`,background:color}}/></div><div className="picker-controls"><div className="selected-color-preview" style={{'--picked':color}}><span>COLOR ACTUAL</span><b>{color}</b></div><label className="hex-label">CÓDIGO HEX<input value={hex} maxLength="7" spellCheck="false" onChange={e=>setHexValue(e.target.value)} aria-label="Código hexadecimal"/></label><label className="brightness-label">LUMINOSIDAD<input type="range" min="18" max="100" value={Math.round(hsv.v*100)} onChange={e=>update({...hsv,v:Number(e.target.value)/100})} style={{'--range-color':color}}/></label><button className="picker-apply" disabled={!/^#?[0-9a-f]{6}$/i.test(hex)} onClick={()=>onApply(hex.startsWith('#')?hex:('#'+hex))}>Aplicar color</button></div></div><div className="quick-palette"><div className="palette-label">PALETA RÁPIDA <span>15 tonos</span></div><div className="palette-swatches">{quick.map(q=><button key={q} className={`palette-swatch${color.toLowerCase()===q.toLowerCase()?' selected':''}`} style={{background:q}} onClick={()=>update(hexToHsv(q))} aria-label={`Elegir ${q}`}/>)}</div></div></section></div>
}
function App(){const [screen,setScreen]=useState('home'),[data,setData]=useState(()=>({...initial,...read('cesba.student',{})})),[owner,setOwner]=useState(''),[photo,setPhoto]=useState(()=>localStorage.getItem('cesba.photo')||''),[careers,setCareers]=useState(()=>read('cesba.careers',SEED)),[flipped,setFlipped]=useState(false),[homeFlipped,setHomeFlipped]=useState(false),[expanded,setExpanded]=useState(false),[pickerIndex,setPickerIndex]=useState(null),[qr,setQr]=useState(''),[newCareer,setNewCareer]=useState(''),[buildKey,setBuildKey]=useState(0),[ripple,setRipple]=useState(null);
 const color=careers.find(c=>c.name===data.career)?.color||'#2463eb';
 const drag=useRef(null);const tap=useRef({time:0,timer:null});const rippleTimer=useRef(null);
 useEffect(()=>{window.setPhoto=(value)=>setPhoto(value||'');window.setQr=(value)=>setQr(value||'');return()=>{delete window.setPhoto;delete window.setQr}},[]);
 useEffect(()=>{window.nativeBack=()=>{if(expanded){setExpanded(false);return 'handled'}if(pickerIndex!==null){setPickerIndex(null);return 'handled'}if(screen==='settings'){setScreen('editor');return 'handled'}if(screen==='editor'){setScreen('home');return 'handled'}return 'exit'};return()=>{delete window.nativeBack}},[screen,expanded,pickerIndex]);
 useEffect(()=>{localStorage.setItem('cesba.student',JSON.stringify(data));localStorage.setItem('cesba.photo',photo);localStorage.setItem('cesba.careers',JSON.stringify(careers));const timer=setTimeout(()=>{if(window.CESBA?.makeQr)window.CESBA.makeQr(JSON.stringify({nombre:data.name||'Nombre y apellidos',matricula:data.matricula||'00000000',carrera:data.career||'Carrera',grupo:data.group||'—',semestre:data.term||'Semestre'}))},180);return()=>clearTimeout(timer)},[data,photo,careers]);
 const patch=(key,value)=>setData(prev=>({...prev,[key]:value}));const start=()=>{if(owner.trim())patch('name',owner.trim());if(!data.career&&careers.length)patch('career',careers[0].name);setFlipped(false);setScreen('editor')};const openSettings=()=>setScreen('settings');const addCareer=()=>{const name=newCareer.trim();if(!name||careers.some(c=>c.name.toLowerCase()===name.toLowerCase()))return;setCareers(prev=>[...prev,{name,color:'#2463eb'}]);setNewCareer('')};const camera=()=>window.CESBA?.openCamera();
 const closeExpanded=()=>setExpanded(false);
 const openExpanded=()=>setExpanded(true);
 const liveCard=(id)=>{const isHome=id==='homeCard'||(id==='expandedCard'&&screen==='home');const isBack=isHome?homeFlipped:flipped;const onStart=e=>{const t=e.changedTouches[0];drag.current={x:t.clientX,y:t.clientY,swiped:false}};const onEnd=e=>{const start=drag.current;if(!start)return;const t=e.changedTouches[0],dx=t.clientX-start.x,dy=t.clientY-start.y;if(Math.abs(dx)>46&&Math.abs(dx)>Math.abs(dy)*1.25){start.swiped=true;setBuildKey(v=>v+1);if(isHome)setHomeFlipped(v=>!v);else setFlipped(v=>!v);setTimeout(()=>{if(drag.current===start)drag.current=null},420)}else drag.current=null};const onClick=()=>{if(drag.current?.swiped){drag.current=null;return}const now=Date.now();if(now-tap.current.time<340){clearTimeout(tap.current.timer);tap.current.time=0;if(!expanded)openExpanded()}else{tap.current.time=now;tap.current.timer=setTimeout(()=>{tap.current.time=0},360)}};const onPointerDown=e=>{const rect=e.currentTarget.querySelector('.card')?.getBoundingClientRect();if(!rect)return;setRipple({x:e.clientX-rect.left,y:e.clientY-rect.top,key:Date.now()});clearTimeout(rippleTimer.current);rippleTimer.current=setTimeout(()=>setRipple(null),950)};return <><div className="card-stage swipe-zone" onTouchStart={onStart} onTouchEnd={onEnd} onPointerDown={onPointerDown} onClick={onClick} role="button" tabIndex="0" aria-label="Doble toque para ampliar; desliza para cambiar el reverso" onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();if(!expanded)openExpanded()}}}><Card data={data} photo={photo} color={color} back={isBack} qr={qr} ripple={ripple} buildKey={buildKey}/></div><div className="swipe-hint">Doble toque para ampliar · desliza en cualquier dirección para girar <span>↔</span></div></>};
 return <main className="shell"><Brand onSettings={openSettings}/>
 {screen==='home'&&<section className="screen active"><div className="home-hero"><div className="hero"><div className="eyebrow">Tu campus. Tu identidad.</div><h1>Una credencial<br/>que habla <span>de ti.</span></h1><p>Diseña tu identificación digital y lleva tu vida académica siempre contigo.</p></div><div className="home-card"><div className="section-label"><span>VISTA PREVIA</span><span className="live-pill"><i/>EN VIVO</span></div>{liveCard('homeCard')}</div><div className="field user-field"><label>NOMBRE DEL TITULAR</label><input value={owner} onChange={e=>{setOwner(e.target.value);patch('name',e.target.value)}} placeholder="Escribe tu nombre completo"/></div><button className="primary full" onClick={start}>Crear mi credencial <span style={{fontSize:16}}>↗</span></button><div className="bottomline">DISEÑADA PARA <i/> COMUNIDAD CESBA</div></div></section>}
 {screen==='editor'&&<section className="screen active editor-screen"><div className="hero editor-hero"><div className="eyebrow">Personaliza tu identidad</div><h1>Tu tarjeta,<br/><span>en tiempo real.</span></h1><p>Escribe tus datos y mira cómo toma forma. Tu foto y cada detalle cuentan.</p></div><div className="editor-columns"><div className="editor-preview-column"><div className="editor-sticky-preview"><div className="section-label"><span>PREVISUALIZACIÓN</span><span className="live-pill"><i/>ACTUALIZACIÓN EN VIVO</span></div>{liveCard('liveCard')}</div></div><div className="editor-form-column"><section className="glass-panel"><div className="formhead"><strong>Datos académicos</strong><span>01 — 06</span></div><div className="field"><label>Nombre completo</label><input value={data.name} onChange={e=>patch('name',e.target.value)} placeholder="Nombre y apellidos" autoComplete="name"/></div><div className="field"><label>Matrícula</label><input value={data.matricula} onChange={e=>patch('matricula',e.target.value)} placeholder="Ej. 24001234"/></div><div className="field"><label>Carrera</label><select value={data.career||careers[0]?.name||''} onChange={e=>patch('career',e.target.value)}>{careers.map(c=><option key={c.name}>{c.name}</option>)}</select></div><div className="grid"><div className="field"><label>Semestre / cuatrimestre</label><input value={data.term} onChange={e=>patch('term',e.target.value)} placeholder="Ej. 4.º semestre"/></div><div className="field"><label>Grupo</label><input value={data.group} onChange={e=>patch('group',e.target.value)} placeholder="Ej. A"/></div></div><div className="field"><label>Correo electrónico</label><input type="email" value={data.email} onChange={e=>patch('email',e.target.value)} placeholder="nombre@cesba.edu.mx" autoComplete="email"/></div><div className="field"><label>Tipo de usuario</label><select value={data.role} onChange={e=>patch('role',e.target.value)}><option>Estudiante</option><option>Docente</option><option>Administrativo</option></select></div><div className="field"><label>Fotografía</label><div className="camera-row"><div className="camera-preview">{photo?<img src={photo} alt="Foto tomada"/>:'＋'}</div><div className="camera-copy">{photo?'Foto lista. Puedes volver a tomarla si quieres.':'Agrega una foto para completar tu credencial.'}</div><button className="camera-btn" onClick={camera}>◉ &nbsp;{photo?'Volver a tomar':'Tomar foto'}</button></div></div><div className="actions"><button className="primary" onClick={()=>{if(!data.name.trim()||!data.matricula.trim()){alert('Añade tu nombre y matrícula para generar la credencial.');return}setFlipped(true);window.scrollTo({top:0,behavior:'smooth'})}}>Generar credencial &nbsp;↗</button><button className="subtle" onClick={()=>setScreen('home')}>Inicio</button></div></section><div className="note">Tus datos se quedan en este dispositivo.</div></div></div></section>}
 {screen==='settings'&&<section className="screen active"><div className="hero"><div className="eyebrow">Tu identidad, a tu manera</div><h1>Colores con<br/><span>carácter.</span></h1><p>Elige la personalidad visual de cada carrera. Los cambios se guardan automáticamente.</p></div><div className="glass-panel"><h2 className="settings-title">Carreras disponibles</h2><p className="settings-copy">Cada carrera tiene un acento de color único en la credencial. Elige cualquier color con el selector; puedes agregar todas las carreras que necesites.</p>{careers.map((c,i)=><div className="career-row" key={c.name}><button className="color-control" style={{background:c.color,"--swatch":c.color}} title={`Personalizar ${c.name}`} onClick={()=>setPickerIndex(i)} aria-label={`Personalizar color de ${c.name}`}><span>✦</span></button><div className="career-name">{c.name}</div><button className="mini-btn delete-btn" onClick={()=>setCareers(prev=>prev.length>1?prev.filter((_,n)=>n!==i):prev)}>Quitar</button></div>)}<div className="add-career"><input value={newCareer} onChange={e=>setNewCareer(e.target.value)} placeholder="Nombre de carrera"/><button onClick={addCareer}>＋ Agregar</button></div></div><button className="primary full" onClick={()=>setScreen('editor')} style={{marginTop:14}}>Guardar y volver</button></section>}
 {expanded&&<div className="credential-fullscreen"><button className="fullscreen-close" onClick={closeExpanded} aria-label="Cerrar vista ampliada">×</button><div className="fullscreen-label">CREDENCIAL DIGITAL <span>·</span> DESLIZA PARA CAMBIAR DE LADO</div>{liveCard('expandedCard')}</div>}
 {pickerIndex!==null&&careers[pickerIndex]&&<ColorPickerDialog initialColor={careers[pickerIndex].color} onCancel={()=>setPickerIndex(null)} onApply={value=>{setCareers(prev=>prev.map((c,i)=>i===pickerIndex?{...c,color:value}:c));setPickerIndex(null)}}/>}
 </main>}

createRoot(document.getElementById('root')).render(<App/>);
window.__CESBA_READY__=true;

