import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const SEED=[{name:'Ingeniería en Sistemas Computacionales',color:'#2463eb'},{name:'Ingeniería Mecatrónica',color:'#e67e22'},{name:'Ingeniería Aeroespacial',color:'#8b5cf6'}];
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const initial={name:'',matricula:'',career:'',term:'',group:'',email:'',role:'Estudiante'};
const esc=(value='')=>String(value);
function Brand({onSettings}){return <header className="topbar"><div className="brand"><div className="seal"><img className="brand-logo" src="./cesba-logo.png" alt="Logo institucional CESBA"/></div></div><button className="iconbtn" aria-label="Ajustes" onClick={onSettings}>⚙</button></header>}
function Card({data,photo,color,back=false,qr=''}){const sparkles=useMemo(()=>Array.from({length:15},(_,i)=><i key={i} className="spark" style={{left:`${(i*37+8)%97}%`,top:`${(i*61+13)%87}%`,width:i%4===0?3:2,height:i%4===0?3:2,animationDelay:`${i%9*.31}s`}}/>),[]);return <article className={`card${back?' card-back':''}`} style={{'--career':color}}>{back?<><h3>IDENTIDAD ACADÉMICA</h3><div className="qrbox">{qr&&<img src={`data:image/png;base64,${qr}`} alt="Código QR con los datos académicos"/>}</div><p>Escanea para consultar los datos académicos del titular.</p><div className="cardfoot" style={{position:'static',width:'100%',marginTop:7}}><span>CESBA · CREDENCIAL DIGITAL</span><b>✦</b></div></>:<><div className="sparkles">{sparkles}</div><div className="cardhead"><div className="cardcrest"><img className="crest-image" src="./cesba-logo.png" alt="Logo CESBA"/></div><div className="school">CREDENCIAL DIGITAL<small>IDENTIFICACIÓN UNIVERSITARIA</small></div><div className="chip"/></div><div className="cardbody"><div className="avatar">{photo?<img src={photo} alt="Foto del estudiante"/>:<span>✦</span>}</div><div className="identity"><div className="tag">{esc(data.role||'Estudiante').toUpperCase()} · {esc(data.matricula||'00000000')}</div><h2>{esc(data.name||'Nombre y apellidos')}</h2><div className="major">{esc(data.career||'Tu carrera')}</div><div className="idrow"><div className="idnum"><label>MATRÍCULA</label><strong>{esc(data.matricula||'00000000')}</strong></div><div className="idterm"><label>PERIODO · GRUPO</label><strong>{esc(data.term||'Semestre')} · {esc(data.group||'—')}</strong></div></div></div></div><div className="cardfoot"><span>{esc(data.email||'correo@cesba.edu.mx')}</span><b>CESBA&nbsp; ✦</b></div></>}</article>}
function App(){const [screen,setScreen]=useState('home'),[data,setData]=useState(()=>({...initial,...read('cesba.student',{})})),[owner,setOwner]=useState(''),[photo,setPhoto]=useState(()=>localStorage.getItem('cesba.photo')||''),[careers,setCareers]=useState(()=>read('cesba.careers',SEED)),[flipped,setFlipped]=useState(false),[qr,setQr]=useState(''),[newCareer,setNewCareer]=useState('');
 const color=careers.find(c=>c.name===data.career)?.color||'#2463eb';
 useEffect(()=>{window.setPhoto=(value)=>setPhoto(value||'');window.setQr=(value)=>setQr(value||'');return()=>{delete window.setPhoto;delete window.setQr}},[]);
 useEffect(()=>{window.nativeBack=()=>{if(screen==='settings'){setScreen('editor');return 'handled'}if(screen==='editor'){setScreen('home');return 'handled'}return 'exit'};return()=>{delete window.nativeBack}},[screen]);
 useEffect(()=>{localStorage.setItem('cesba.student',JSON.stringify(data));localStorage.setItem('cesba.photo',photo);localStorage.setItem('cesba.careers',JSON.stringify(careers));const timer=setTimeout(()=>{if(window.CESBA?.makeQr)window.CESBA.makeQr(JSON.stringify({nombre:data.name||'Nombre y apellidos',matricula:data.matricula||'00000000',carrera:data.career||'Carrera',grupo:data.group||'—',semestre:data.term||'Semestre'}))},180);return()=>clearTimeout(timer)},[data,photo,careers]);
 const patch=(key,value)=>setData(prev=>({...prev,[key]:value}));const start=()=>{if(owner.trim())patch('name',owner.trim());if(!data.career&&careers.length)patch('career',careers[0].name);setFlipped(false);setScreen('editor')};const openSettings=()=>setScreen('settings');const addCareer=()=>{const name=newCareer.trim();if(!name||careers.some(c=>c.name.toLowerCase()===name.toLowerCase()))return;setCareers(prev=>[...prev,{name,color:'#2463eb'}]);setNewCareer('')};const cycleColor=i=>{const palette=['#2463eb','#e67e22','#8b5cf6','#00a88f','#da4771','#09a0c2','#c69413','#536dfe'];setCareers(prev=>prev.map((c,n)=>n===i?{...c,color:palette[(palette.indexOf(c.color)+1+palette.length)%palette.length]}:c))};const camera=()=>window.CESBA?.openCamera();
 const liveCard=(id)=> <div className="card-stage"><Card data={data} photo={photo} color={color} back={flipped&&id==='liveCard'} qr={qr}/></div>;
 return <main className="shell"><Brand onSettings={openSettings}/>
 {screen==='home'&&<section className="screen active"><div className="home-hero"><div className="hero"><div className="eyebrow">Tu campus. Tu identidad.</div><h1>Una credencial<br/>que habla <span>de ti.</span></h1><p>Diseña tu identificación digital y lleva tu vida académica siempre contigo.</p></div><div className="home-card"><div className="section-label"><span>VISTA PREVIA</span><span className="live-pill"><i/>EN VIVO</span></div>{liveCard('homeCard')}</div><div className="field user-field"><label>NOMBRE DEL TITULAR</label><input value={owner} onChange={e=>{setOwner(e.target.value);patch('name',e.target.value)}} placeholder="Escribe tu nombre completo"/></div><button className="primary full" onClick={start}>Crear mi credencial <span style={{fontSize:16}}>↗</span></button><div className="bottomline">DISEÑADA PARA <i/> COMUNIDAD CESBA</div></div></section>}
 {screen==='editor'&&<section className="screen active"><div className="hero"><div className="eyebrow">Personaliza tu identidad</div><h1>Tu tarjeta,<br/><span>en tiempo real.</span></h1><p>Escribe tus datos y mira cómo toma forma. Tu foto y cada detalle cuentan.</p></div><div className="section-label"><span>PREVISUALIZACIÓN</span><span className="live-pill"><i/>ACTUALIZACIÓN EN VIVO</span></div>{liveCard('liveCard')}<div className="flip-controls"><button className={`segment ${!flipped?'active':''}`} onClick={()=>setFlipped(false)}>Frente de tarjeta</button><button className={`segment ${flipped?'active':''}`} onClick={()=>setFlipped(true)}>Reverso · QR</button></div><section className="glass-panel"><div className="formhead"><strong>Datos académicos</strong><span>01 — 06</span></div><div className="field"><label>Nombre completo</label><input value={data.name} onChange={e=>patch('name',e.target.value)} placeholder="Nombre y apellidos" autoComplete="name"/></div><div className="field"><label>Matrícula</label><input value={data.matricula} onChange={e=>patch('matricula',e.target.value)} placeholder="Ej. 24001234"/></div><div className="field"><label>Carrera</label><select value={data.career||careers[0]?.name||''} onChange={e=>patch('career',e.target.value)}>{careers.map(c=><option key={c.name}>{c.name}</option>)}</select></div><div className="grid"><div className="field"><label>Semestre / cuatrimestre</label><input value={data.term} onChange={e=>patch('term',e.target.value)} placeholder="Ej. 4.º semestre"/></div><div className="field"><label>Grupo</label><input value={data.group} onChange={e=>patch('group',e.target.value)} placeholder="Ej. A"/></div></div><div className="field"><label>Correo electrónico</label><input type="email" value={data.email} onChange={e=>patch('email',e.target.value)} placeholder="nombre@cesba.edu.mx" autoComplete="email"/></div><div className="field"><label>Tipo de usuario</label><select value={data.role} onChange={e=>patch('role',e.target.value)}><option>Estudiante</option><option>Docente</option><option>Administrativo</option></select></div><div className="field"><label>Fotografía</label><div className="camera-row"><div className="camera-preview">{photo?<img src={photo} alt="Foto tomada"/>:'＋'}</div><div className="camera-copy">{photo?'Foto lista. Puedes volver a tomarla si quieres.':'Agrega una foto para completar tu credencial.'}</div><button className="camera-btn" onClick={camera}>◉ &nbsp;{photo?'Volver a tomar':'Tomar foto'}</button></div></div><div className="actions"><button className="primary" onClick={()=>{if(!data.name.trim()||!data.matricula.trim()){alert('Añade tu nombre y matrícula para generar la credencial.');return}setFlipped(true);window.scrollTo({top:0,behavior:'smooth'})}}>Generar credencial &nbsp;↗</button><button className="subtle" onClick={()=>setScreen('home')}>Inicio</button></div></section><div className="note">Tus datos se quedan en este dispositivo.</div></section>}
 {screen==='settings'&&<section className="screen active"><div className="hero"><div className="eyebrow">Tu identidad, a tu manera</div><h1>Colores con<br/><span>carácter.</span></h1><p>Elige la personalidad visual de cada carrera. Los cambios se guardan automáticamente.</p></div><div className="glass-panel"><h2 className="settings-title">Carreras disponibles</h2><p className="settings-copy">Cada carrera tiene un acento de color único en la credencial. Toca la muestra de color para cambiarla.</p>{careers.map((c,i)=><div className="career-row" key={c.name}><button className="color-dot" style={{background:c.color,color:c.color}} onClick={()=>cycleColor(i)} aria-label={`Cambiar color de ${c.name}`}/><div className="career-name">{c.name}</div><button className="mini-btn delete-btn" onClick={()=>setCareers(prev=>prev.length>1?prev.filter((_,n)=>n!==i):prev)}>Quitar</button></div>)}<div className="add-career"><input value={newCareer} onChange={e=>setNewCareer(e.target.value)} placeholder="Nombre de carrera"/><button onClick={addCareer}>＋ Agregar</button></div></div><button className="primary full" onClick={()=>setScreen('editor')} style={{marginTop:14}}>Guardar y volver</button></section>}
 </main>}

createRoot(document.getElementById('root')).render(<App/>);
window.__CESBA_READY__=true;

